name: "Terraform Pull Request Commenter Curl Patched"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output. The output should be written to a file first."
author: "Allan Dalton"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  commenter_type:
    description: "The type of comment. Options: [fmt, init, plan]."
    required: true
  input_file:
    description: "Path to the file containing the output to comment on."
    required: true
  commenter_exitcode:
    description: "The exit code from a previous step output."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.commenter_type }}
    - ${{ inputs.input_file }}
    - ${{ inputs.commenter_exitcode }}
