name: "Terraform Pull Request Commenter Curl Patched"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output."
author: "Allan Dalton"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  commenter_type:
    description: "The type of comment. Options: [fmt, init, plan]."
    required: true
  commenter_input:
    description: "The comment to post from a previous step output."
    required: true
  commenter_exitcode:
    description: "The exit code from a previous step output."
    required: true
runs:
  using: "composite"
  steps:
    - name: Write input to file
      shell: bash
      run: |
        echo "${{ inputs.commenter_input }}" > /tmp/terraform_output.txt
    - name: Run commenter
      uses: docker://ghcr.io/helloallan/terraform-pull-request-commenter:latest
      with:
        args: ${{ inputs.commenter_type }} /tmp/terraform_output.txt ${{ inputs.commenter_exitcode }}
